oidc_providers:
  - uid: "aaa58fc5-0397-495d-8cb5-92b02559d376"
    allowed_attached_email_domains:
      - domain: preprod.suiteterritoriale.fr
        source: routed
      - domain: sardinepq.fr
        source: routed
