oidc_providers:
  - uid: "f5154035-c3d6-47ad-8583-197d508269d0"
    allowed_attached_email_domains:
      - domain: adico.collectivite.fr
        source: manual
      - domain: adm81.collectivite.fr
        source: manual
      - domain: aiglun06.fr
        source: manual
      - domain: ainhoa.fr
        source: dila
      - domain: aletlesbains.com
        source: manual
      - domain: alpi.collectivite.fr
        source: manual
      - domain: alzon.fr
        source: dila
      - domain: amf.collectivite.fr
        source: manual
      - domain: arnia.collectivite.fr
        source: manual
      - domain: arzenc-de-randon.fr
        source: dila
      - domain: at86.collectivite.fr
        source: manual
      - domain: atd24.collectivite.fr
        source: manual
      - domain: aubreville.fr
        source: manual
      - domain: ayros-arbouix.fr
        source: manual
      - domain: azoudange.fr
        source: manual
      - domain: badaroux.fr
        source: manual
      - domain: belloy-en-france.fr
        source: dila
      - domain: belmont-bretenoux.fr
        source: manual
      - domain: berrelesalpes.fr
        source: manual
      - domain: blars.fr
        source: manual
      - domain: boisseron.fr
        source: dila
      - domain: bouranton.fr
        source: manual
      - domain: brigny.collectivite.fr
        source: manual
      - domain: caille06.fr
        source: manual
      - domain: carayac.collectivite.fr
        source: manual
      - domain: castellet-en-luberon.collectivite.fr
        source: manual
      - domain: cdg09.collectivite.fr
        source: manual
      - domain: cdg47.collectivite.fr
        source: manual
      - domain: cdg48.collectivite.fr
        source: manual
      - domain: charleval13.fr
        source: manual
      - domain: charlevalenprovence.fr
        source: manual
      - domain: chateauneuflerouge.fr
        source: dila
      - domain: chaudeyrac.fr
        source: dila
      - domain: chaumeil19.fr
        source: manual
      - domain: cipieres.fr
        source: manual
      - domain: commune-montmaur.fr
        source: dila
      - domain: condamine.fr
        source: dila
      - domain: coublucq.fr
        source: dila
      - domain: courlandon.fr
        source: dila
      - domain: courson-monteloup.fr
        source: dila
      - domain: crepon14.fr
        source: manual
      - domain: demo.collectivite.fr
        source: manual
      - domain: ecollectivites.collectivite.fr
        source: manual
      - domain: ecuras.fr
        source: dila
      - domain: ecury-sur-coole.fr
        source: dila
      - domain: fajoles.fr
        source: manual
      - domain: ferrieres-les-bois.fr
        source: manual
      - domain: feuguerolles-bully.fr
        source: dila
      - domain: fibre5962.collectivite.fr
        source: manual
      - domain: frontenac.fr
        source: dila
      - domain: garderes.fr
        source: dila
      - domain: gennes25.fr
        source: manual
      - domain: gieconvergence.collectivite.fr
        source: manual
      - domain: girondenumerique.collectivite.fr
        source: manual
      - domain: gourdon06.fr
        source: manual
      - domain: grandfailly.fr
        source: manual
      - domain: griesbachauval.fr
        source: dila
      - domain: griselles21.collectivite.fr
        source: manual
      - domain: houdelaincourt.fr
        source: dila
      - domain: lacaunette34.fr
        source: dila
      - domain: lacelle19.fr
        source: manual
      - domain: ladignedaval.fr
        source: manual
      - domain: lafibre64.collectivite.fr
        source: manual
      - domain: lemesnilsuroger.fr
        source: manual
      - domain: les-aspres.collectivite.fr
        source: manual
      - domain: les-salles-lavauguyon.fr
        source: manual
      - domain: lescun.fr
        source: dila
      - domain: letouvet.fr
        source: manual
      - domain: lgnum.collectivite.fr
        source: manual
      - domain: lignieres-sur-aire.fr
        source: manual
      - domain: lolif.fr
        source: manual
      - domain: louvigny64.fr
        source: manual
      - domain: mairie-beaurecueil.fr
        source: dila
      - domain: mairie-cauge.fr
        source: dila
      - domain: mairie-celon.fr
        source: manual
      - domain: mairie-de-jabreilles-les-bordes.fr
        source: manual
      - domain: mairie-de-maron.fr
        source: manual
      - domain: mairie-de-salins.fr
        source: dila
      - domain: mairie-ibos.fr
        source: manual
      - domain: mairie-onoz.fr
        source: dila
      - domain: mairie-puttelangeauxlacs.fr
        source: dila
      - domain: mairie-savins.fr
        source: manual
      - domain: mairiedelouey.fr
        source: manual
      - domain: mairiedestill.fr
        source: manual
      - domain: manchenumerique.collectivite.fr
        source: manual
      - domain: maxey-sur-vaise.fr
        source: manual
      - domain: megalis.collectivite.fr
        source: manual
      - domain: mirabeau84.fr
        source: manual
      - domain: molieres-cavaillac.fr
        source: dila
      - domain: mommenheim.fr
        source: dila
      - domain: montgeroult.fr
        source: dila
      - domain: montgesty.collectivite.fr
        source: manual
      - domain: moselle-fibre.collectivite.fr
        source: manual
      - domain: moulinneuf09.collectivite.fr
        source: manual
      - domain: moulinssurorne.fr
        source: manual
      - domain: moussy.fr
        source: manual
      - domain: nerislesbains.fr
        source: manual
      - domain: neuvy51.fr
        source: manual
      - domain: norroypam.fr
        source: manual
      - domain: oms.fr
        source: dila
      - domain: oradour-sur-vayres.fr
        source: dila
      - domain: outrepont.fr
        source: manual
      - domain: peyroules.fr
        source: manual
      - domain: pointenoire.fr
        source: manual
      - domain: pouliacq.fr
        source: manual
      - domain: putangeslelac.fr
        source: dila
      - domain: puycapel.fr
        source: dila
      - domain: rebenacq.fr
        source: manual
      - domain: recia.collectivite.fr
        source: manual
      - domain: rgd.collectivite.fr
        source: manual
      - domain: sacoue.fr
        source: manual
      - domain: saint-arey.fr
        source: manual
      - domain: saint-bauzile.fr
        source: manual
      - domain: saint-gerons.fr
        source: dila
      - domain: saint-goussaud.fr
        source: manual
      - domain: saint-quentin-sur-isere.fr
        source: dila
      - domain: saint-regle.fr
        source: manual
      - domain: saint-sozy.fr
        source: manual
      - domain: saintbresson.fr
        source: manual
      - domain: saintgermaindejoux.fr
        source: dila
      - domain: saintlaurentdecondel.fr
        source: dila
      - domain: saintrambertenbugey.fr
        source: dila
      - domain: sariac-magnoac.collectivite.fr
        source: manual
      - domain: sauvagnon.fr
        source: dila
      - domain: sauvelade.fr
        source: manual
      - domain: savas.fr
        source: dila
      - domain: servas.fr
        source: dila
      - domain: sidec-jura.com
        source: manual
      - domain: sieeen.collectivite.fr
        source: manual
      - domain: sitiv.collectivite.fr
        source: manual
      - domain: sitiv2.collectivite.fr
        source: manual
      - domain: sivergues.collectivite.fr
        source: manual
      - domain: smic88.collectivite.fr
        source: manual
      - domain: smico.collectivite.fr
        source: manual
      - domain: smn76.collectivite.fr
        source: manual
      - domain: strenquels.fr
        source: manual
      - domain: suite.anct.gouv.fr
        source: manual
      - domain: suiteterritoriale.anct.gouv.fr
        source: manual
      - domain: syane.collectivite.fr
        source: manual
      - domain: test-lst-securite.fr
        source: manual
      - domain: teyssieu.fr
        source: manual
      - domain: tourneville.fr
        source: manual
      - domain: tramoyes.fr
        source: dila
      - domain: trefols.fr
        source: manual
      - domain: trizac.fr
        source: dila
      - domain: valdufaby.fr
        source: manual
      - domain: vaucouleurs.fr
        source: dila
      - domain: vercors.fr
        source: manual
      - domain: vers-pontdugard.fr
        source: manual
      - domain: village-borderes.fr
        source: dila
      - domain: village-le-saix.fr
        source: manual
      - domain: villecloye.fr
        source: dila
      - domain: villedeguillestre.fr
        source: dila
      - domain: villeneuve-saint-denis.fr
        source: manual
      - domain: villeneuve-st-denis.fr
        source: manual
      - domain: villers-allerand.fr
        source: dila
      - domain: villetelle.fr
        source: manual
      - domain: villette-sur-ain.fr
        source: dila
      - domain: violes.fr
        source: dila
