oidc_providers:
  - uid: "f5154035-c3d6-47ad-8583-197d508269d0"
    allowed_fqdns:
      - adico.collectivite.fr
      - adm81.collectivite.fr
      - aiglun06.fr
      - ainhoa.fr
      - aletlesbains.com
      - alpi.collectivite.fr
      - alzon.fr
      - amf.collectivite.fr
      - arnia.collectivite.fr
      - arzenc-de-randon.fr
      - at86.collectivite.fr
      - atd24.collectivite.fr
      - aubreville.fr
      - ayros-arbouix.fr
      - azoudange.fr
      - badaroux.fr
      - belloy-en-france.fr
      - belmont-bretenoux.fr
      - berrelesalpes.fr
      - blars.fr
      - boisseron.fr
      - bouranton.fr
      - brigny.collectivite.fr
      - caille06.fr
      - carayac.collectivite.fr
      - castellet-en-luberon.collectivite.fr
      - cdg09.collectivite.fr
      - cdg47.collectivite.fr
      - cdg48.collectivite.fr
      - charleval13.fr
      - charlevalenprovence.fr
      - chateauneuflerouge.fr
      - chaudeyrac.fr
      - chaumeil19.fr
      - cipieres.fr
      - commune-montmaur.fr
      - condamine.fr
      - coublucq.fr
      - courlandon.fr
      - courson-monteloup.fr
      - crepon14.fr
      - demo.collectivite.fr
      - ecollectivites.collectivite.fr
      - ecuras.fr
      - ecury-sur-coole.fr
      - fajoles.fr
      - ferrieres-les-bois.fr
      - feuguerolles-bully.fr
      - fibre5962.collectivite.fr
      - frontenac.fr
      - garderes.fr
      - gennes25.fr
      - gieconvergence.collectivite.fr
      - girondenumerique.collectivite.fr
      - gourdon06.fr
      - grandfailly.fr
      - griesbachauval.fr
      - griselles21.collectivite.fr
      - houdelaincourt.fr
      - lacaunette34.fr
      - lacelle19.fr
      - ladignedaval.fr
      - lafibre64.collectivite.fr
      - lemesnilsuroger.fr
      - les-aspres.collectivite.fr
      - les-salles-lavauguyon.fr
      - lescun.fr
      - letouvet.fr
      - lgnum.collectivite.fr
      - lignieres-sur-aire.fr
      - lolif.fr
      - louvigny64.fr
      - mairie-beaurecueil.fr
      - mairie-cauge.fr
      - mairie-celon.fr
      - mairie-de-jabreilles-les-bordes.fr
      - mairie-de-maron.fr
      - mairie-de-salins.fr
      - mairie-ibos.fr
      - mairie-onoz.fr
      - mairie-puttelangeauxlacs.fr
      - mairie-savins.fr
      - mairiedelouey.fr
      - mairiedestill.fr
      - manchenumerique.collectivite.fr
      - maxey-sur-vaise.fr
      - megalis.collectivite.fr
      - mirabeau84.fr
      - molieres-cavaillac.fr
      - mommenheim.fr
      - montgeroult.fr
      - montgesty.collectivite.fr
      - moselle-fibre.collectivite.fr
      - moulinneuf09.collectivite.fr
      - moulinssurorne.fr
      - moussy.fr
      - nerislesbains.fr
      - neuvy51.fr
      - norroypam.fr
      - oms.fr
      - oradour-sur-vayres.fr
      - outrepont.fr
      - peyroules.fr
      - pointenoire.fr
      - pouliacq.fr
      - putangeslelac.fr
      - puycapel.fr
      - rebenacq.fr
      - recia.collectivite.fr
      - rgd.collectivite.fr
      - sacoue.fr
      - saint-arey.fr
      - saint-bauzile.fr
      - saint-gerons.fr
      - saint-goussaud.fr
      - saint-quentin-sur-isere.fr
      - saint-regle.fr
      - saint-sozy.fr
      - saintbresson.fr
      - saintgermaindejoux.fr
      - saintlaurentdecondel.fr
      - saintrambertenbugey.fr
      - sariac-magnoac.collectivite.fr
      - sauvagnon.fr
      - sauvelade.fr
      - savas.fr
      - servas.fr
      - sidec-jura.com
      - sieeen.collectivite.fr
      - sitiv.collectivite.fr
      - sitiv2.collectivite.fr
      - sivergues.collectivite.fr
      - smic88.collectivite.fr
      - smico.collectivite.fr
      - smn76.collectivite.fr
      - strenquels.fr
      - suite.anct.gouv.fr
      - suiteterritoriale.anct.gouv.fr
      - syane.collectivite.fr
      - test-lst-securite.fr
      - teyssieu.fr
      - tourneville.fr
      - tramoyes.fr
      - trefols.fr
      - trizac.fr
      - valdufaby.fr
      - vaucouleurs.fr
      - vercors.fr
      - vers-pontdugard.fr
      - village-borderes.fr
      - village-le-saix.fr
      - villecloye.fr
      - villedeguillestre.fr
      - villeneuve-saint-denis.fr
      - villeneuve-st-denis.fr
      - villers-allerand.fr
      - villetelle.fr
      - villette-sur-ain.fr
      - violes.fr
