import { describe, expect, test } from "bun:test";
import { decrypt_symetric, encrypt_symetric } from "./crypt";

// fixture generated by pcdbapi (federation/pcdbapi/test_crypt.py) — pins byte-for-byte
// compatibility with client_secret values already encrypted and stored by pcdbapi in Mongo
const CLIENT_SECRET_CIPHER_PASS = "JZBlwxfKnbn/RV025aw+dQxk+xoQT+Yr";
const PCDBAPI_ENCODED =
  "+sqGL4XE6aqzIMOp/DKC1jWB8I+8qE1jW6iz2tUv8lt+ZZzxjyoCBQeuAcJTFZxfLywkn6cAICK5JPLxYM0+8pk/q7CGHUfr/gzr3ZYRroWWE+egEEDxqRYDYe0=";
const PCDBAPI_DECODED =
  "a970fc88b3111fcfdce515c2ee03488d8a349e5379a3ba2aa48c225dcea243a5";

describe("pcdbapi encryption compatibility", () => {
  test("decrypts a value encrypted by pcdbapi", () => {
    expect(decrypt_symetric(CLIENT_SECRET_CIPHER_PASS, PCDBAPI_ENCODED)).toBe(
      PCDBAPI_DECODED,
    );
  });

  test("round-trips with a random nonce", () => {
    const encrypted = encrypt_symetric(
      CLIENT_SECRET_CIPHER_PASS,
      "secret de test",
    );
    expect(decrypt_symetric(CLIENT_SECRET_CIPHER_PASS, encrypted)).toBe(
      "secret de test",
    );
  });

  test("rejects a cipher that is too short", () => {
    const short_cipher = Buffer.from("too_short").toString("base64");
    expect(() =>
      decrypt_symetric(CLIENT_SECRET_CIPHER_PASS, short_cipher),
    ).toThrow("Authentication failed!");
  });

  test("rejects a forged tag", () => {
    const decoded = Buffer.from(PCDBAPI_ENCODED, "base64");
    const corrupted = Buffer.concat([
      decoded.subarray(0, 12),
      Buffer.alloc(16),
      decoded.subarray(28),
    ]);
    expect(() =>
      decrypt_symetric(CLIENT_SECRET_CIPHER_PASS, corrupted.toString("base64")),
    ).toThrow("Authentication failed!");
  });

  test("rejects a key that is not 32 bytes, but only at the call site", () => {
    expect(() => encrypt_symetric("too-short", "hello")).toThrow();
  });
});

describe("nonce handling (AES-GCM)", () => {
  test("two encryptions of the same plaintext never reuse a nonce", () => {
    const key = "test-cipher-pass-32-bytes-long!!";
    const plaintext = "a".repeat(40);

    const encrypted_a = encrypt_symetric(key, plaintext);
    const encrypted_b = encrypt_symetric(key, plaintext);

    const nonce_a = Buffer.from(encrypted_a, "base64").subarray(0, 12);
    const nonce_b = Buffer.from(encrypted_b, "base64").subarray(0, 12);

    expect(nonce_a.equals(nonce_b)).toBe(false);
  });
});
