import { describe, expect, test } from "bun:test";
import { decrypt_symetric, encrypt_symetric } from "./crypt";

// fixture generated by pcdbapi (federation/pcdbapi/test_crypt.py) — pins byte-for-byte
// compatibility with client_secret values already encrypted and stored by pcdbapi in Mongo
const CLIENT_SECRET_CIPHER_PASS = "JZBlwxfKnbn/RV025aw+dQxk+xoQT+Yr";
const PCDBAPI_ENCODED =
  "+sqGL4XE6aqzIMOp/DKC1jWB8I+8qE1jW6iz2tUv8lt+ZZzxjyoCBQeuAcJTFZxfLywkn6cAICK5JPLxYM0+8pk/q7CGHUfr/gzr3ZYRroWWE+egEEDxqRYDYe0=";
const PCDBAPI_DECODED =
  "a970fc88b3111fcfdce515c2ee03488d8a349e5379a3ba2aa48c225dcea243a5";

describe("compatibilité chiffrement avec pcdbapi", () => {
  test("déchiffre une valeur chiffrée par pcdbapi", () => {
    expect(decrypt_symetric(CLIENT_SECRET_CIPHER_PASS, PCDBAPI_ENCODED)).toBe(
      PCDBAPI_DECODED,
    );
  });

  test("rechiffre à l'identique avec le même nonce", () => {
    const nonce = Buffer.from(PCDBAPI_ENCODED, "base64").subarray(0, 12);
    expect(
      encrypt_symetric(CLIENT_SECRET_CIPHER_PASS, PCDBAPI_DECODED, nonce),
    ).toBe(PCDBAPI_ENCODED);
  });

  test("fait un aller-retour avec un nonce aléatoire", () => {
    const encrypted = encrypt_symetric(
      CLIENT_SECRET_CIPHER_PASS,
      "secret de test",
    );
    expect(decrypt_symetric(CLIENT_SECRET_CIPHER_PASS, encrypted)).toBe(
      "secret de test",
    );
  });

  test("rejette un cipher trop court", () => {
    const short_cipher = Buffer.from("too_short").toString("base64");
    expect(() =>
      decrypt_symetric(CLIENT_SECRET_CIPHER_PASS, short_cipher),
    ).toThrow("Authentication failed!");
  });

  test("rejette un tag falsifié", () => {
    const decoded = Buffer.from(PCDBAPI_ENCODED, "base64");
    const corrupted = Buffer.concat([
      decoded.subarray(0, 12),
      Buffer.alloc(16),
      decoded.subarray(28),
    ]);
    expect(() =>
      decrypt_symetric(CLIENT_SECRET_CIPHER_PASS, corrupted.toString("base64")),
    ).toThrow("Authentication failed!");
  });

  test("rejette une clé qui ne fait pas 32 octets, mais seulement à l'appel", () => {
    // config_schema (src/config.ts) accepts any string for CLIENT_SECRET_CIPHER_PASS —
    // a wrong-length key only fails here, at first encrypt/decrypt call, not at boot.
    // See config.test.ts's matching case.
    expect(() => encrypt_symetric("too-short", "hello")).toThrow();
  });
});

// The `nonce` parameter of encrypt_symetric exists only so the fixture-pinning
// test above can force pcdbapi's exact nonce. It's still part of the public
// signature, so nothing stops a real caller from reusing one: this proves why
// that's not a style nitpick — a reused nonce under AES-GCM makes the two
// ciphertexts' XOR equal the two plaintexts' XOR, i.e. leaks both secrets
// without ever touching the key.
describe("réutilisation de nonce (AES-GCM) — pourquoi le paramètre public est dangereux", () => {
  test("deux chiffrements avec le même nonce laissent fuiter le XOR des deux secrets en clair", () => {
    const key = "test-cipher-pass-32-bytes-long!!";
    const reused_nonce = Buffer.alloc(12, 7);
    const secret_a = "a".repeat(40);
    const secret_b = "b".repeat(40);

    const encrypted_a = encrypt_symetric(key, secret_a, reused_nonce);
    const encrypted_b = encrypt_symetric(key, secret_b, reused_nonce);

    // ciphertext layout is nonce(12) + tag(16) + ciphertext
    const ciphertext_a = Buffer.from(encrypted_a, "base64").subarray(28);
    const ciphertext_b = Buffer.from(encrypted_b, "base64").subarray(28);
    const ciphertext_xor = Buffer.alloc(ciphertext_a.length);
    for (let i = 0; i < ciphertext_a.length; i++) {
      ciphertext_xor[i] = ciphertext_a[i]! ^ ciphertext_b[i]!;
    }

    const plaintext_xor = Buffer.alloc(secret_a.length);
    for (let i = 0; i < secret_a.length; i++) {
      plaintext_xor[i] = secret_a.charCodeAt(i) ^ secret_b.charCodeAt(i);
    }

    expect(ciphertext_xor.equals(plaintext_xor)).toBe(true);
  });
});
